export const clients = new Map();
export const sceneImages = [];
export const sceneCharacters = [];
export const sceneTokens = [];
export const blockedVerticalEdges = new Set();
export const blockedHorizontalEdges = new Set();
export const sceneDoors = new Map();
export const sceneRooms = new Map();
export const chatMessages = [];
