import {
  BrickWall,
  BrushCleaning,
  DoorOpen,
  EyeOff,
  LandPlot,
  MessageCircle,
  Package,
  RefreshCw,
  Trash2,
  Upload,
  Users,
  createIcons,
} from "lucide";
import { mustGetCanvasContext, mustQuery, mustQueryAll } from "../utilities/dom";

export function queryDomRefs() {
  const canvas = mustQuery<HTMLCanvasElement>("#world-canvas");
  const ctx = mustGetCanvasContext(canvas);
  const latencyPanel = document.createElement("aside");
  latencyPanel.className = "latency-panel";
  latencyPanel.hidden = true;
  document.body.append(latencyPanel);

  const diceOverlayRoot = document.createElement("div");
  diceOverlayRoot.className = "dice-overlay-root";
  diceOverlayRoot.setAttribute("aria-hidden", "true");
  document.body.append(diceOverlayRoot);

  const diceHiddenLogContainer = document.createElement("div");
  diceHiddenLogContainer.className = "dice-hidden-log";
  diceHiddenLogContainer.hidden = true;
  document.body.append(diceHiddenLogContainer);

  createIcons({
    icons: {
      BrickWall,
      BrushCleaning,
      DoorOpen,
      EyeOff,
      LandPlot,
      MessageCircle,
      Package,
      RefreshCw,
      Trash2,
      Upload,
      Users,
    },
    nameAttr: "data-lucide",
    attrs: {
      "aria-hidden": "true",
      class: "tool-icon",
      focusable: "false",
    },
  });

  return {
    canvas,
    ctx,
    latencyPanel,
    diceOverlayRoot,
    diceHiddenLogContainer,
    identityScreen: mustQuery<HTMLElement>("#identity-screen"),
    identityList: mustQuery<HTMLDivElement>("#identity-list"),
    modeToggle: mustQuery<HTMLDivElement>("#mode-toggle"),
    modeToggleOptions: mustQueryAll<HTMLButtonElement>("#mode-toggle .mode-toggle-option"),
    editModeSelectLabel: mustQuery<HTMLLabelElement>(".edit-mode-select-label"),
    editModeSelect: mustQuery<HTMLSelectElement>("#edit-mode-select"),
    uploadButton: mustQuery<HTMLLabelElement>("#upload-button"),
    uploadInput: mustQuery<HTMLInputElement>("#image-upload"),
    wallModeButton: mustQuery<HTMLButtonElement>("#wall-mode-button"),
    doorModeButton: mustQuery<HTMLButtonElement>("#door-mode-button"),
    roomModeButton: mustQuery<HTMLButtonElement>("#room-mode-button"),
    clearWallsButton: mustQuery<HTMLButtonElement>("#clear-walls-button"),
    logicMapVisibilityButton: mustQuery<HTMLButtonElement>("#logic-map-visibility-button"),
    switchIdentityButton: mustQuery<HTMLButtonElement>("#switch-identity-button"),
    chatToggleButton: mustQuery<HTMLButtonElement>("#chat-toggle-button"),
    characterToggleButton: mustQuery<HTMLButtonElement>("#character-toggle-button"),
    identityBadge: mustQuery<HTMLSpanElement>("#identity-badge"),
    dropOverlay: mustQuery<HTMLDivElement>("#drop-overlay"),
    chatPanel: mustQuery<HTMLElement>("#chat-panel"),
    chatCloseButton: mustQuery<HTMLButtonElement>("#chat-close-button"),
    chatMessageList: mustQuery<HTMLDivElement>("#chat-message-list"),
    characterPanel: mustQuery<HTMLElement>("#character-panel"),
    characterCloseButton: mustQuery<HTMLButtonElement>("#character-close-button"),
    addCharacterButton: mustQuery<HTMLButtonElement>("#add-character-button"),
    characterList: mustQuery<HTMLDivElement>("#character-list"),
    itemToggleButton: mustQuery<HTMLButtonElement>("#item-toggle-button"),
    itemPanel: mustQuery<HTMLElement>("#item-panel"),
    itemCloseButton: mustQuery<HTMLButtonElement>("#item-close-button"),
    addItemButton: mustQuery<HTMLButtonElement>("#add-item-button"),
    itemList: mustQuery<HTMLDivElement>("#item-list"),
    itemDefinitionInspectorOverlay: mustQuery<HTMLElement>("#item-definition-inspector-overlay"),
    closeItemDefinitionInspectorButton: mustQuery<HTMLButtonElement>("#close-item-definition-inspector"),
    itemDefinitionSelectionForm: mustQuery<HTMLFormElement>("#item-definition-selection-form"),
    itemNameDisplay: mustQuery<HTMLDivElement>("#item-name-display"),
    itemNameValue: mustQuery<HTMLSpanElement>("#item-name-value"),
    editItemNameButton: mustQuery<HTMLButtonElement>("#edit-item-name"),
    itemNameInput: mustQuery<HTMLInputElement>("#item-name-input"),
    itemDescriptionInput: mustQuery<HTMLTextAreaElement>("#item-description-input"),
    itemIconUploadButton: mustQuery<HTMLLabelElement>("#item-icon-upload-button"),
    itemIconUploadInput: mustQuery<HTMLInputElement>("#item-icon-upload-input"),
    itemIconAdjustControls: mustQuery<HTMLDivElement>("#item-icon-adjust-controls"),
    editItemIconButton: mustQuery<HTMLButtonElement>("#edit-item-icon"),
    resetItemIconAdjustmentButton: mustQuery<HTMLButtonElement>("#reset-item-icon-adjustment"),
    deleteItemDefinitionButton: mustQuery<HTMLButtonElement>("#delete-item-definition"),
    itemDefinitionPanelHelp: mustQuery<HTMLParagraphElement>("#item-definition-panel-help"),
    itemInstanceInspectorOverlay: mustQuery<HTMLElement>("#item-instance-inspector-overlay"),
    closeItemInstanceInspectorButton: mustQuery<HTMLButtonElement>("#close-item-instance-inspector"),
    itemInstanceSelectionForm: mustQuery<HTMLFormElement>("#item-instance-selection-form"),
    itemInstanceIconPreview: mustQuery<HTMLDivElement>("#item-instance-icon-preview"),
    itemInstanceNameValue: mustQuery<HTMLSpanElement>("#item-instance-name-value"),
    itemInstanceDescriptionValue: mustQuery<HTMLParagraphElement>("#item-instance-description-value"),
    itemInstanceQuantityValue: mustQuery<HTMLSpanElement>("#item-instance-quantity-value"),
    itemInstanceQuantityEdit: mustQuery<HTMLLabelElement>("#item-instance-quantity-edit"),
    itemQuantityInput: mustQuery<HTMLInputElement>("#item-quantity-input"),
    deleteItemInstanceButton: mustQuery<HTMLButtonElement>("#delete-item-instance"),
    splitItemInstanceButton: mustQuery<HTMLButtonElement>("#split-item-instance"),
    takeItemInstanceButton: mustQuery<HTMLButtonElement>("#take-item-instance"),
    discardItemInstanceButton: mustQuery<HTMLButtonElement>("#discard-item-instance"),
    itemSplitPopover: mustQuery<HTMLDivElement>("#item-split-popover"),
    itemSplitSlider: mustQuery<HTMLInputElement>("#item-split-slider"),
    itemSplitValue: mustQuery<HTMLOutputElement>("#item-split-value"),
    cancelItemSplitButton: mustQuery<HTMLButtonElement>("#cancel-item-split"),
    confirmItemSplitButton: mustQuery<HTMLButtonElement>("#confirm-item-split"),
    avatarEditorTitle: mustQuery<HTMLHeadingElement>("#avatar-editor-title"),
    selectionPanel: mustQuery<HTMLDivElement>("#selection-panel"),
    selectionEyebrow: mustQuery<HTMLDivElement>("#selection-eyebrow"),
    selectionTitle: mustQuery<HTMLDivElement>("#selection-title"),
    imageSelectionControls: mustQuery<HTMLDivElement>("#image-selection-controls"),
    imageSelectionActions: mustQuery<HTMLDivElement>("#image-selection-actions"),
    imageSelectionDanger: mustQuery<HTMLDivElement>("#image-selection-danger"),
    resetSizeButton: mustQuery<HTMLButtonElement>("#reset-size"),
    layerUpButton: mustQuery<HTMLButtonElement>("#layer-up"),
    layerDownButton: mustQuery<HTMLButtonElement>("#layer-down"),
    layerTopButton: mustQuery<HTMLButtonElement>("#layer-top"),
    layerBottomButton: mustQuery<HTMLButtonElement>("#layer-bottom"),
    deleteImageButton: mustQuery<HTMLButtonElement>("#delete-image"),
    tokenSelectionForm: mustQuery<HTMLFormElement>("#token-selection-form"),
    tokenNameDisplay: mustQuery<HTMLDivElement>("#token-name-display"),
    tokenNameValue: mustQuery<HTMLSpanElement>("#token-name-value"),
    editTokenNameButton: mustQuery<HTMLButtonElement>("#edit-token-name"),
    tokenNameInput: mustQuery<HTMLInputElement>("#token-name-input"),
    avatarUploadButton: mustQuery<HTMLLabelElement>("#avatar-upload-button"),
    avatarUploadInput: mustQuery<HTMLInputElement>("#avatar-upload-input"),
    avatarAdjustControls: mustQuery<HTMLDivElement>("#avatar-adjust-controls"),
    editAvatarButton: mustQuery<HTMLButtonElement>("#edit-avatar"),
    resetAvatarAdjustmentButton: mustQuery<HTMLButtonElement>("#reset-avatar-adjustment"),
    tokenPanelHelp: mustQuery<HTMLParagraphElement>("#token-panel-help"),
    tokenNpcTypeControls: mustQuery<HTMLDivElement>("#token-npc-type-controls"),
    tokenNpcTypeInput: mustQuery<HTMLInputElement>("#token-npc-type-input"),
    tokenInspectorTabStats: mustQuery<HTMLButtonElement>("#token-inspector-tab-stats"),
    tokenInspectorTabProfile: mustQuery<HTMLButtonElement>("#token-inspector-tab-profile"),
    tokenInspectorTabBackpack: mustQuery<HTMLButtonElement>("#token-inspector-tab-backpack"),
    tokenInspectorTabBackground: mustQuery<HTMLButtonElement>("#token-inspector-tab-background"),
    tokenStatsPanel: mustQuery<HTMLDivElement>("#token-stats-panel"),
    tokenStatsList: mustQuery<HTMLDivElement>("#token-stats-list"),
    tokenProfilePanel: mustQuery<HTMLDivElement>("#token-profile-panel"),
    tokenBackpackPanel: mustQuery<HTMLDivElement>("#token-backpack-panel"),
    tokenBackpackTitle: mustQuery<HTMLDivElement>("#token-backpack-title"),
    tokenBackpackList: mustQuery<HTMLDivElement>("#token-backpack-list"),
    tokenBackpackHelp: mustQuery<HTMLParagraphElement>("#token-backpack-help"),
    tokenBackgroundPanel: mustQuery<HTMLDivElement>("#token-background-panel"),
    tokenBackgroundList: mustQuery<HTMLDivElement>("#token-background-list"),
    tokenInspectorOverlay: mustQuery<HTMLElement>("#token-inspector-overlay"),
    closeTokenInspectorButton: mustQuery<HTMLButtonElement>("#close-token-inspector"),
    tokenInstanceActions: mustQuery<HTMLDivElement>("#token-instance-actions"),
    deleteTokenInstanceButton: mustQuery<HTMLButtonElement>("#delete-token-instance"),
    doorSelectionForm: mustQuery<HTMLFormElement>("#door-selection-form"),
    doorBlocksMovementInput: mustQuery<HTMLInputElement>("#door-blocks-movement-input"),
    roomSelectionForm: mustQuery<HTMLFormElement>("#room-selection-form"),
    roomNameInput: mustQuery<HTMLInputElement>("#room-name-input"),
    deleteRoomButton: mustQuery<HTMLButtonElement>("#delete-room"),
    avatarEditorOverlay: mustQuery<HTMLElement>("#avatar-editor-overlay"),
    avatarEditorStage: mustQuery<HTMLDivElement>("#avatar-editor-stage"),
    avatarEditorImage: mustQuery<HTMLImageElement>("#avatar-editor-image"),
    cancelAvatarEditButton: mustQuery<HTMLButtonElement>("#cancel-avatar-edit"),
    saveAvatarEditButton: mustQuery<HTMLButtonElement>("#save-avatar-edit"),
    dicePanel: mustQuery<HTMLElement>("#dice-panel"),
    diceFocusLabel: mustQuery<HTMLButtonElement>("#dice-focus-label"),
    diceOptionButtons: Array.from(document.querySelectorAll<HTMLButtonElement>(".dice-option")),
    diceAdjustButtons: Array.from(document.querySelectorAll<HTMLButtonElement>(".dice-adjust-button[data-die]")),
    diceRollButton: mustQuery<HTMLButtonElement>("#dice-roll"),
    diceModifierInput: mustQuery<HTMLInputElement>("#dice-modifier"),
    diceModifierDecreaseButton: mustQuery<HTMLButtonElement>("#dice-modifier-decrease"),
    diceModifierIncreaseButton: mustQuery<HTMLButtonElement>("#dice-modifier-increase"),
    warehouseOverlay: mustQuery<HTMLElement>("#warehouse-overlay"),
    closeWarehouseOverlayButton: mustQuery<HTMLButtonElement>("#close-warehouse-overlay"),
    warehouseOverlayEyebrow: mustQuery<HTMLParagraphElement>("#warehouse-overlay-eyebrow"),
    warehouseOverlayTitle: mustQuery<HTMLHeadingElement>("#warehouse-overlay-title"),
    warehouseSingleView: mustQuery<HTMLDivElement>("#warehouse-single-view"),
    warehouseSingleList: mustQuery<HTMLDivElement>("#warehouse-single-list"),
    warehouseTransferView: mustQuery<HTMLDivElement>("#warehouse-transfer-view"),
    warehouseTransferGroundTitle: mustQuery<HTMLDivElement>("#warehouse-transfer-ground-title"),
    warehouseTransferGroundList: mustQuery<HTMLDivElement>("#warehouse-transfer-ground-list"),
    warehouseTransferBackpackTitle: mustQuery<HTMLDivElement>("#warehouse-transfer-backpack-title"),
    warehouseTransferBackpackList: mustQuery<HTMLDivElement>("#warehouse-transfer-backpack-list"),
    warehouseOverlayHelp: mustQuery<HTMLParagraphElement>("#warehouse-overlay-help"),
  };
}
